import { beforeEach, describe, expect, it, vi } from "vitest";

const authMock = vi.hoisted(() => ({ authenticateSessionRequest: vi.fn() }));
const storeMock = vi.hoisted(() => ({
  createAuditEvent: vi.fn(),
}));
const hardeningMock = vi.hoisted(() => ({
  checkRateLimit: vi.fn(),
  ensureRequestId: vi.fn(),
}));
const orchestratorMock = vi.hoisted(() => ({
  runAgentOrchestration: vi.fn(),
}));

vi.mock("@/lib/session-request-auth", () => authMock);
vi.mock("@/lib/milestone1-store", () => storeMock);
vi.mock("@/lib/hardening", () => hardeningMock);
vi.mock("@/lib/milestone5-agent-orchestrator", () => orchestratorMock);

import { POST } from "./route";

const OWNER_A = { id: "owner-1", email: "owner-a@example.com", role: "professional", locale: "en" };

function invoke(body: unknown, headers: Record<string, string> = {}): Promise<Response> {
  const request = new Request("http://localhost/api/v1/agents/orchestrate", {
    method: "POST",
    headers: { "Content-Type": "application/json", ...headers },
    body: JSON.stringify(body),
  });
  return POST(request);
}

const HONEST_RESULT = {
  requestId: "req-fixed",
  steps: [
    { agent: "planner", status: "skipped", summary: "No real planning agent is available yet; this step did not run and produced no plan." },
    { agent: "safety", status: "skipped", summary: "No real safety-policy agent is available yet; no safety checks were performed." },
    { agent: "domain", status: "skipped", summary: "No real domain-reasoning agent is available yet; no domain analysis was performed." },
    { agent: "formatter", status: "skipped", summary: "No real formatting agent is available yet; no output was generated by this step." },
  ],
  output: { taskType: "consultation", status: "not_available", message: "Real multi-agent orchestration is not implemented yet. No planning, safety validation, domain reasoning, or recommendation was performed for this request." },
};

beforeEach(() => {
  vi.clearAllMocks();
  authMock.authenticateSessionRequest.mockResolvedValue(OWNER_A);
  hardeningMock.checkRateLimit.mockReturnValue({ allowed: true, remaining: 39 });
  hardeningMock.ensureRequestId.mockReturnValue("req-fixed");
  orchestratorMock.runAgentOrchestration.mockReturnValue(HONEST_RESULT);
});

describe("POST /api/v1/agents/orchestrate", () => {
  it("returns 401 without a cookie, never touching the orchestrator or the rate limiter", async () => {
    authMock.authenticateSessionRequest.mockResolvedValue(null);

    const response = await invoke({ taskType: "consultation", payload: {} });

    expect(response.status).toBe(401);
    expect(hardeningMock.checkRateLimit).not.toHaveBeenCalled();
    expect(orchestratorMock.runAgentOrchestration).not.toHaveBeenCalled();
  });

  it("returns 401 for an unknown or expired session (no in-memory fallback)", async () => {
    authMock.authenticateSessionRequest.mockResolvedValue(null);

    const response = await invoke({ taskType: "consultation", payload: {} });

    expect(response.status).toBe(401);
  });

  it("returns 429 when the rate limit is exceeded, never touching the orchestrator", async () => {
    hardeningMock.checkRateLimit.mockReturnValue({ allowed: false, remaining: 0 });

    const response = await invoke({ taskType: "consultation", payload: {} });

    expect(response.status).toBe(429);
    expect(orchestratorMock.runAgentOrchestration).not.toHaveBeenCalled();
  });

  it("returns 400 when taskType is missing", async () => {
    const response = await invoke({ payload: {} });
    expect(response.status).toBe(400);
    expect(orchestratorMock.runAgentOrchestration).not.toHaveBeenCalled();
  });

  it("returns 400 when payload is missing or not an object", async () => {
    const response = await invoke({ taskType: "consultation", payload: "not-an-object" });
    expect(response.status).toBe(400);
    expect(orchestratorMock.runAgentOrchestration).not.toHaveBeenCalled();
  });

  it("returns the orchestrator's honest result unchanged, with no fabricated fields added by the route", async () => {
    const response = await invoke({ taskType: "consultation", payload: { goal: "refresh" } });

    expect(response.status).toBe(200);
    const body = await response.json();
    expect(body).toEqual(HONEST_RESULT);
    expect(body.steps.every((step: { status: string }) => step.status === "skipped")).toBe(true);
    expect(body.output).not.toHaveProperty("confidence");
    expect(body.output).not.toHaveProperty("recommendation");
  });

  it("records an audit event for the request without persisting the fabricated content", async () => {
    await invoke({ taskType: "consultation", payload: { goal: "refresh" } });

    expect(storeMock.createAuditEvent).toHaveBeenCalledWith({
      ownerUserId: "owner-1",
      requestId: "req-fixed",
      module: "agents",
      action: "orchestration_executed",
      metadata: { taskType: "consultation", steps: 4 },
    });
  });

  it("scopes the audit event and rate limit strictly to the authenticated owner (cross-user isolation)", async () => {
    authMock.authenticateSessionRequest.mockResolvedValue({
      id: "owner-2",
      email: "owner-b@example.com",
      role: "professional",
      locale: "en",
    });

    await invoke({ taskType: "consultation", payload: { goal: "refresh" } });

    expect(hardeningMock.checkRateLimit).toHaveBeenCalledWith("agents-orchestrate:owner-2", 40, 60_000);
    expect(storeMock.createAuditEvent).toHaveBeenCalledWith(
      expect.objectContaining({ ownerUserId: "owner-2" }),
    );
  });
});
