import { randomUUID } from "crypto";

import type { AgentOrchestrateRequest, AgentOrchestrateResponse, AgentStepResult } from "@/lib/contracts";

// No real planner/safety/domain/formatter agent exists yet (M23). Every step
// must honestly report "skipped" -- never "ok" -- since none of them
// actually ran: claiming "ok" on the safety step in particular would be a
// false safety-verification claim, not just a cosmetic placeholder.
const NOT_AVAILABLE_SUMMARY: Record<AgentStepResult["agent"], string> = {
  planner: "No real planning agent is available yet; this step did not run and produced no plan.",
  safety: "No real safety-policy agent is available yet; no safety checks were performed.",
  domain: "No real domain-reasoning agent is available yet; no domain analysis was performed.",
  formatter: "No real formatting agent is available yet; no output was generated by this step."
};

const ORCHESTRATION_AGENTS = ["planner", "safety", "domain", "formatter"] as const;

export function runAgentOrchestration(input: AgentOrchestrateRequest): AgentOrchestrateResponse {
  const requestId = input.requestId?.trim() || randomUUID();

  const steps: AgentStepResult[] = ORCHESTRATION_AGENTS.map((agent) => ({
    agent,
    status: "skipped",
    summary: NOT_AVAILABLE_SUMMARY[agent]
  }));

  return {
    requestId,
    steps,
    output: {
      taskType: input.taskType,
      status: "not_available",
      message:
        "Real multi-agent orchestration is not implemented yet. No planning, safety validation, domain reasoning, or recommendation was performed for this request."
    }
  };
}
