import { randomUUID } from "crypto";

import type { ImageAsset } from "@prisma/client";

import {
  ObjectStorageWriteModeRequiredError,
  resolveObjectStorageWriteTarget,
  resolveRuntimeMode,
  writeImageToObjectStorage,
} from "@/lib/image-analysis-service";
import { processImageForStorage } from "@/lib/image-normalizer";
import { saveImageFile } from "@/lib/image-storage";
import { prisma } from "@/lib/prisma";

// Real AI Photo Preview, Stage 2 -- persists a provider's generated bytes
// as a brand-new, durable ImageAsset row (task §15/§16/§17):
//
// - Reuses the EXACT same durable storage decision an uploaded photo goes
//   through (resolveObjectStorageWriteTarget / writeImageToObjectStorage
//   from image-analysis-service.ts) -- never a second, competing storage
//   path, and never allowed to silently land only on Railway's ephemeral
//   local disk in production (ObjectStorageWriteModeRequiredError, same
//   as uploads).
// - Reuses processImageForStorage (image-normalizer.ts) for the same
//   EXIF-strip/re-encode/dimension-read pipeline an upload gets -- so a
//   generated image's own persisted width/height are computed the exact
//   same way every other ImageAsset's are, not a second implementation.
// - Always creates a NEW ImageAsset row with a NEW id -- never overwrites
//   the source ImageAsset (task §16). `origin: "ai_generated"` is the
//   Stage 1-decided provenance/trust-boundary discriminator: this is what
//   makes it structurally impossible to confuse a generated preview with
//   a real client upload later (e.g. it can never accidentally become new
//   Analysis evidence just by matching a bare imageAssetId).

export const PHOTO_PREVIEW_OUTPUT_ORIGIN = "ai_generated";

export class PhotoPreviewOutputStorageError extends Error {
  constructor(message: string) {
    super(message);
    this.name = "PhotoPreviewOutputStorageError";
  }
}

export async function persistGeneratedPhotoPreviewImage(
  ownerUserId: string,
  clientId: string,
  imageBuffer: Buffer,
  mimeType: string,
): Promise<ImageAsset> {
  const objectStorageTarget = resolveObjectStorageWriteTarget();

  if (!objectStorageTarget && resolveRuntimeMode(process.env.NODE_ENV) === "production") {
    throw new ObjectStorageWriteModeRequiredError();
  }

  let processed: { buffer: Buffer; orientation: number; exifStripped: boolean; width: number; height: number };
  try {
    processed = await processImageForStorage(imageBuffer, mimeType);
  } catch (error) {
    throw new PhotoPreviewOutputStorageError(error instanceof Error ? error.message : "Failed to process generated image.");
  }

  const asset = await prisma.imageAsset.create({
    data: {
      id: randomUUID(),
      fileName: `photo-preview-${Date.now()}.${extensionForMimeType(mimeType)}`,
      mimeType,
      sizeBytes: processed.buffer.length,
      ownerUserId,
      clientId,
      storagePath: "pending",
      origin: PHOTO_PREVIEW_OUTPUT_ORIGIN,
      exifStripped: processed.exifStripped,
      normalizedOrientation: processed.orientation,
      width: processed.width,
      height: processed.height,
    },
  });

  try {
    if (objectStorageTarget) {
      await writeImageToObjectStorage(asset, processed.buffer, mimeType, objectStorageTarget);
    } else {
      const storagePath = await saveImageFile(ownerUserId, asset.id, asset.fileName, processed.buffer);
      await prisma.imageAsset.update({ where: { id: asset.id }, data: { storagePath } });
    }
  } catch (error) {
    // The row already exists (id allocated above) but storage write failed
    // -- left exactly as-is (storageBackend=null, storagePath="pending"),
    // matching the exact same fail-closed shape an upload's own storage
    // failure leaves. The caller (photo-preview-execution-service.ts) is
    // responsible for treating this as PHOTO_PREVIEW_STORAGE_FAILED and
    // never marking the parent generation COMPLETED.
    throw new PhotoPreviewOutputStorageError(error instanceof Error ? error.message : "Failed to persist generated image to durable storage.");
  }

  return prisma.imageAsset.findUniqueOrThrow({ where: { id: asset.id } });
}

function extensionForMimeType(mimeType: string): string {
  if (mimeType === "image/png") return "png";
  if (mimeType === "image/webp") return "webp";
  return "jpg";
}
