import { readFileSync, readdirSync } from "node:fs";
import path from "node:path";
import ts from "typescript";
import { describe, expect, it } from "vitest";
import { ELEVATION_OPTIONS, SECTIONING_OPTIONS, GUIDELINE_OPTIONS } from "./proposal-validators";
import { conceptDigest, LEGACY_MAPPING_CORRESPONDENCES, PROFESSIONAL_VALIDATION_REQUIRED } from "./professional-concept-contracts";
import { canonicalValueDigest } from "./professional-canonical-value-contracts";
import { definitionDigest } from "./professional-definition-contracts";
import { freezeProfessionalPack, isValidProfessionalConceptPack, type ProfessionalConceptPack } from "./professional-concept-registry";
import { CUTTING_PROFESSIONAL_CONCEPT_PACK as pack } from "./professional-concept-cutting-pack";

const clone = () => structuredClone(pack);
// Re-pin deliberate synthetic mutations so tests reach structural checks rather
// than merely failing because the mutation left a stale digest.
function repin(p: ProfessionalConceptPack): ProfessionalConceptPack {
  const canonicalValues = p.canonicalValues.map(v => ({ ...v, semanticDigest: canonicalValueDigest(v) }));
  const concepts = p.concepts.map(c => {
    const next = { ...c, canonicalValues: c.canonicalValues?.map(ref => {
      const value = canonicalValues.find(v => v.conceptId === ref.conceptId && v.valueToken === ref.valueToken);
      return value ? { ...ref, semanticDigest: value.semanticDigest } : ref;
    }) };
    return { ...next, specificationDigest: conceptDigest(next) };
  });
  return { ...p, concepts, canonicalValues, definitions: p.definitions.map(d => ({ ...d, specificationDigest: definitionDigest(d) })) };
}
describe("O1 registry and real-case boundaries", () => {
  it("registers exactly five identities and only existing value tokens", () => {
    expect(pack.concepts.map(c => c.conceptId)).toEqual(["haircutting.elevation", "haircutting.sectioning", "haircutting.guideType", "haircutting.cuttingAngle", "haircutting.cuttingLine"]);
    for (const [i, tokens] of [ELEVATION_OPTIONS, SECTIONING_OPTIONS, GUIDELINE_OPTIONS].entries()) expect(pack.concepts[i].canonicalValues?.map(v => v.valueToken)).toEqual(tokens);
    expect(pack.canonicalValues).toHaveLength(14);
    expect(pack.concepts.slice(3).every(c => c.canonicalValues === undefined && c.status === undefined)).toBe(true);
    expect(isValidProfessionalConceptPack(pack)).toBe(true);
    expect(isValidProfessionalConceptPack(clone())).toBe(true);
    expect(JSON.stringify(freezeProfessionalPack(clone()))).toBe(JSON.stringify(pack));
    expect(Object.isFrozen(pack.canonicalValues[0].localizedLabels)).toBe(true);
  });
  it("pins deterministic semantic goldens for all five concepts", () => {
    // Versioned fixtures, reviewed explicitly; never regenerated by tests/build.
    const goldens = { "1.0.0-t162c2a": {
      "haircutting.elevation": "sha256:ec9b50d9826f25ef21c233901710ac9a8281eca9e50c0240fc2538f033a57e78",
      "haircutting.sectioning": "sha256:686436a6666bb69bec32ab12d585763b12d79ab9083291b57fa80e35b52b6fb7",
      "haircutting.guideType": "sha256:065e87ddd29c86bcf00a61a2bb0706f6f1712dbb16c7b4688d761b1892376714",
      "haircutting.cuttingAngle": "sha256:3f0b4021c4797f2800bb224ba82e036876acc8039e1f63550f63e26bb8fabd58",
      "haircutting.cuttingLine": "sha256:81b9136cafcee80741f964030df07ea4f355d6e03070a7e3105a16e2ec276823",
    } };
    expect(pack.specificationVersion).toBe("1.0.0-t162c2a");
    expect(Object.fromEntries(pack.concepts.map(c => [c.conceptId, c.specificationDigest]))).toEqual(goldens["1.0.0-t162c2a"]);
  });
  it("rejects duplicate IDs, values, references and stale versions/digests", () => {
    expect(isValidProfessionalConceptPack({ ...pack, concepts: [...pack.concepts, pack.concepts[0]] })).toBe(false);
    expect(isValidProfessionalConceptPack({ ...pack, canonicalValues: [...pack.canonicalValues, pack.canonicalValues[0]] })).toBe(false);
    const p = clone(); p.concepts[0] = { ...p.concepts[0], canonicalValues: [...p.concepts[0].canonicalValues!, p.concepts[0].canonicalValues![0]] };
    expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
    expect(isValidProfessionalConceptPack({ ...pack, specificationVersion: "2.0.0" })).toBe(false);
    expect(isValidProfessionalConceptPack({ ...pack, specificationVersion: "v1" })).toBe(false);
    const stale = clone(); stale.concepts[0] = { ...stale.concepts[0], scope: "ACTION" };
    expect(isValidProfessionalConceptPack(stale)).toBe(false);
  });
  it("rejects alias collisions with tokens, themselves and other aliases", () => {
    for (const aliases of [[{ alias: ELEVATION_OPTIONS[1], classification: "LEGACY_ALIAS" as const }], [{ alias: "test_alias", classification: "LEGACY_ALIAS" as const }, { alias: "test_alias", classification: "LEGACY_ALIAS" as const }]]) {
      const p = clone(); p.canonicalValues[0] = { ...p.canonicalValues[0], legacyAliases: aliases };
      expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
    }
    const p = clone(); for (const i of [0, 1]) p.canonicalValues[i] = { ...p.canonicalValues[i], legacyAliases: [{ alias: "same_alias", classification: "LEGACY_ALIAS" }] };
    expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
  });
  it.each(["AMBIGUOUS", "NEEDS_SPLIT"] as const)("%s cannot be loosened by any correspondence", status => {
    for (const correspondence of LEGACY_MAPPING_CORRESPONDENCES) {
      const p = clone(); p.concepts[0] = { ...p.concepts[0], status };
      p.canonicalValues = p.canonicalValues.map(v => v.conceptId === p.concepts[0].conceptId ? { ...v, status } : v);
      p.canonicalValues[0] = { ...p.canonicalValues[0], status, legacyMappingCorrespondence: [{ targetModelRef: "test-only", targetDimension: "test-only", correspondence }] };
      expect(isValidProfessionalConceptPack(repin(p))).toBe(true);
      for (const unsafe of ["CANONICAL", "LEGACY_ALIAS", "DEPRECATED"] as const) {
        p.canonicalValues[0] = { ...p.canonicalValues[0], status: unsafe };
        expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
      }
    }
  });
  it.each(["PRECEDES", "FOLLOWS", "PART_OF", "CONTAINS", "REQUIRES", "CONSTRAINS", "APPLIES_TO"] as const)("rejects %s cycles after re-pinning", kind => {
    const p = clone();
    for (const i of [0, 1, 2]) p.concepts[i] = { ...p.concepts[i], relationships: [{ kind, targetConceptId: p.concepts[(i + 1) % 3].conceptId }] };
    expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
  });
  it("normalizes inverse pairs without rejecting a consistent inverse assertion", () => {
    const p = clone();
    p.concepts[0] = { ...p.concepts[0], relationships: [{ kind: "PRECEDES", targetConceptId: p.concepts[1].conceptId }] };
    p.concepts[1] = { ...p.concepts[1], relationships: [{ kind: "FOLLOWS", targetConceptId: p.concepts[0].conceptId }] };
    expect(isValidProfessionalConceptPack(repin(p))).toBe(true);
    p.concepts[0] = { ...p.concepts[0], relationships: [{ kind: "REQUIRES", targetConceptId: "missing.concept" }] };
    expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
    p.concepts[0] = { ...p.concepts[0], relationships: [{ kind: "REQUIRES", targetConceptId: p.concepts[0].conceptId }] };
    expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
  });
  it("rejects unknown relationship kinds and conflicting legacy classifications", () => {
    const p = clone();
    p.concepts[0] = Object.assign({}, p.concepts[0], { relationships: [{ kind: "SIMILAR_TO", targetConceptId: p.concepts[1].conceptId }] });
    expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
    const q = clone();
    q.concepts[0] = { ...q.concepts[0], legacyMappings: [{ token: ELEVATION_OPTIONS[0], classification: "CANONICAL" }] };
    expect(isValidProfessionalConceptPack(repin(q))).toBe(false);
  });
  it("checks definition references and distinguishFrom integrity", () => {
    const p: ProfessionalConceptPack = { ...clone(), definitions: [{ definitionId: "test.definition", conceptId: "haircutting.elevation", text: PROFESSIONAL_VALIDATION_REQUIRED, scope: PROFESSIONAL_VALIDATION_REQUIRED, distinguishFrom: ["missing.concept"], provenance: { sourceId: "test", authorityType: "test", reviewedAt: "2026-01-01" }, specificationVersion: pack.specificationVersion, specificationDigest: pack.concepts[0].specificationDigest }] };
    expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
    const q = clone(); q.canonicalValues[0] = { ...q.canonicalValues[0], semanticMeaning: "missing.definition" };
    expect(isValidProfessionalConceptPack(repin(q))).toBe(false);
  });
  it("keeps 45-degree elevation separate from both unresolved cutting geometry shells", () => {
    expect(pack.canonicalValues.find(v => v.valueToken === "45_deg_graduation")?.conceptId).toBe("haircutting.elevation");
    expect(pack.concepts.slice(3).every(c => !c.canonicalValues?.length && c.scope === PROFESSIONAL_VALIDATION_REQUIRED)).toBe(true);
    expect(pack.concepts.every(c => !c.relationships?.length)).toBe(true);
  });
  it("does not accept private local observations as global canonical content", () => {
    for (const scope of ["SUBSECTION", "OBSERVATION_WINDOW", "ACTION"]) {
      const observation = { scope, rawObservation: "thin vertical/slanted working sections", ownerUserId: "private-test", decision: "CONFIRMED" };
      expect(isValidProfessionalConceptPack({ ...pack, observations: [observation] })).toBe(false);
      const p = clone(); p.concepts[1] = Object.assign({}, p.concepts[1], observation);
      expect(isValidProfessionalConceptPack(repin(p))).toBe(false);
    }
    // No assignment of the private fixture's scope to the shared concept.
    expect(pack.concepts[1].scope).toBe(PROFESSIONAL_VALIDATION_REQUIRED);
    expect(pack.concepts.some(c => /subsectioning|parting/.test(c.conceptId))).toBe(false);
  });
  it("does not flatten the rich guide model or manufacture missing dimensions", () => {
    const guide = pack.canonicalValues.filter(v => v.conceptId === "haircutting.guideType");
    expect(guide.map(v => v.status)).toEqual(Array(4).fill("AMBIGUOUS"));
    expect(guide.map(v => v.legacyMappingCorrespondence![0].correspondence)).toEqual(["PARTIAL", "PARTIAL", "AMBIGUOUS_CORRESPONDENCE", "NO_MAPPING"]);
    expect(guide[3].legacyMappingCorrespondence![0].targetValue).toBeUndefined();
    const source = readFileSync("src/lib/professional-skill-guide-relationship-contracts.ts", "utf8");
    for (const dimension of ["GuideSource", "GuideRole", "GuideBehavior", "GuideSectionRelationship", "OverdirectionRelationship", "GuideProgressionState", "ReferenceProgressionState"]) expect(source).toContain(dimension);
  });
});

const modules = ["professional-concept-contracts", "professional-canonical-value-contracts", "professional-definition-contracts", "professional-concept-registry", "professional-concept-cutting-pack"];
function sources(dir: string): string[] {
  return readdirSync(dir, { withFileTypes: true }).flatMap(e => e.isDirectory() ? sources(path.join(dir, e.name)) : /\.[cm]?[jt]sx?$/.test(e.name) && !/\.(test|spec)\./.test(e.name) ? [path.join(dir, e.name)] : []);
}
describe("O1 production isolation", () => {
  it("has zero consumers anywhere in the existing production source tree", () => {
    const consumers: string[] = [];
    for (const file of sources(path.resolve("src"))) {
      if (modules.some(m => file === path.resolve(`src/lib/${m}.ts`))) continue;
      const source = readFileSync(file, "utf8");
      const ast = ts.createSourceFile(file, source, ts.ScriptTarget.Latest, true);
      const visit = (node: ts.Node) => {
        if (ts.isStringLiteralLike(node) && modules.some(m => node.text.includes(m))) consumers.push(file);
        if (ts.isIdentifier(node) && ["CUTTING_PROFESSIONAL_CONCEPT_PACK", "isValidProfessionalConceptPack"].includes(node.text)) consumers.push(file);
        ts.forEachChild(node, visit);
      };
      visit(ast);
    }
    expect(consumers).toEqual([]);
  });
  it("imports only pure vocabulary dependencies; contains no DB, decision, provider, binding or activation calls", () => {
    const allowed = new Set(["node:crypto", "@/lib/technical-visual-map-validators", "@/lib/proposal-validators", "@/lib/analysis-field-options", ...modules.map(m => `./${m}`)]);
    for (const moduleName of modules) {
      const ast = ts.createSourceFile(moduleName, readFileSync(`src/lib/${moduleName}.ts`, "utf8"), ts.ScriptTarget.Latest, true);
      const visit = (node: ts.Node) => {
        if (ts.isImportDeclaration(node)) expect(allowed.has((node.moduleSpecifier as ts.StringLiteral).text)).toBe(true);
        if (ts.isCallExpression(node)) {
          expect(node.expression.kind).not.toBe(ts.SyntaxKind.ImportKeyword);
          if (ts.isIdentifier(node.expression)) expect(["require", "fetch", "eval", "Function", "resolveAlias", "bindToSkill", "activate", "execute", "run"]).not.toContain(node.expression.text);
        }
        ts.forEachChild(node, visit);
      };
      visit(ast);
    }
    // All three existing dependencies import types only: even the Prisma types
    // in proposal-validators are erased and cannot instantiate a DB client.
    for (const name of ["proposal-validators", "analysis-field-options", "technical-visual-map-validators"]) {
      const ast = ts.createSourceFile(name, readFileSync(`src/lib/${name}.ts`, "utf8"), ts.ScriptTarget.Latest, true);
      for (const statement of ast.statements) if (ts.isImportDeclaration(statement)) expect(statement.importClause?.isTypeOnly).toBe(true);
    }
  });
});
