import { readFileSync } from "node:fs";
import ts from "typescript";
import { describe, expect, it } from "vitest";
import historicalPack from "./__fixtures__/professional-concept-pack-1.1.0-t162c2a1.json";
import { conceptDigest, isConceptId, isProfessionalConcept, isProfessionalScope, PROFESSIONAL_VALIDATION_REQUIRED } from "./professional-concept-contracts";
import { canonicalValueDigest } from "./professional-canonical-value-contracts";
import { freezeProfessionalPack, isValidProfessionalConceptPack, type ProfessionalConceptPack } from "./professional-concept-registry";
import { DISTRIBUTION_OPTIONS, ELEVATION_OPTIONS } from "./proposal-validators";
import { GUIDE_BEHAVIORS, OVERDIRECTION_RELATIONSHIPS } from "./professional-skill-guide-relationship-contracts";

const newIds = ["haircutting.section", "haircutting.subsection", "haircutting.subsectioning", "haircutting.parting", "haircutting.projection", "haircutting.overdirection", "haircutting.guide"];
// Released O1.1 remains a literal historical artifact, never regenerated by tests.
const pack = freezeProfessionalPack(historicalPack as ProfessionalConceptPack);
const newConcepts = pack.concepts.slice(5);

describe("O1.1 approved identity expansion", () => {
  it("adds exactly the seven authorized identities with no extra identity", () => {
    expect(pack.concepts).toHaveLength(12);
    expect(newConcepts.map(c => c.conceptId)).toEqual(newIds);
    expect(new Set(pack.concepts.map(c => c.conceptId)).size).toBe(12);
    expect(pack.concepts.every(isProfessionalConcept)).toBe(true);
    expect(isValidProfessionalConceptPack(pack)).toBe(true);
    expect(pack.concepts.some(c => /partingDirection|45Interior|guide\./.test(c.conceptId))).toBe(false);
  });
  it.each(newIds)("keeps %s an unresolved shell without semantics or values", id => {
    const c = pack.concepts.find(c => c.conceptId === id)!;
    expect(c).toEqual({ conceptId: id, canonicalName: id.split(".")[1], vertical: "cutting",
      conceptType: PROFESSIONAL_VALIDATION_REQUIRED, scope: PROFESSIONAL_VALIDATION_REQUIRED,
      observability: PROFESSIONAL_VALIDATION_REQUIRED, relationships: [], legacyMappings: [],
      specificationVersion: "1.1.0-t162c2a1", specificationDigest: conceptDigest(c) });
    expect(pack.canonicalValues.filter(v => v.conceptId === id)).toEqual([]);
  });
  it("pins seven new deterministic shell digests", () => {
    // Reviewed versioned fixtures; never regenerated by tests/build.
    const goldens = { "1.1.0-t162c2a1": {
      "haircutting.section": "sha256:08437c8d59395e7a8177303aba41bdca8c6793cc31469742f6d84e3feddb7ab0",
      "haircutting.subsection": "sha256:4cbd9591cd18a178d892c42e95563f6c2bd4976930db4eab2ef7e7638e941fc6",
      "haircutting.subsectioning": "sha256:c167fde94a9bfb3c4b1fe1c47fe7d4c664143b0a76309e3549f95adcf09a41b1",
      "haircutting.parting": "sha256:fdb78223fdcb3627335de3f6bba88c530c8a9d44f56e016dd3968c623bf6fe21",
      "haircutting.projection": "sha256:f81fc0510cf248bb4623cc784a8c18251d90843f3364c1d3755c3084207c0e6a",
      "haircutting.overdirection": "sha256:d98bd2553e70b8301d758cbeeb792ac748e493628a0fc6de8e6655ba5d087521",
      "haircutting.guide": "sha256:395d58fda9c55157671a58e71f7c37b2378ec2363e3d67e0977b1d61b7b399ba",
    } };
    expect(Object.fromEntries(newConcepts.map(c => [c.conceptId, c.specificationDigest]))).toEqual(goldens["1.1.0-t162c2a1"]);
    expect(newConcepts.every(c => conceptDigest(structuredClone(c)) === c.specificationDigest)).toBe(true);
  });
  it("uses uniform version labels without changing concept or value digests", () => {
    expect(pack.specificationVersion).toBe("1.1.0-t162c2a1");
    for (const c of pack.concepts) {
      expect(c.specificationVersion).toBe(pack.specificationVersion);
      expect(conceptDigest({ ...c, specificationVersion: "1.0.0-t162c2a", canonicalValues: c.canonicalValues?.map(r => ({ ...r, semanticVersion: "1.0.0-t162c2a" })) })).toBe(c.specificationDigest);
      expect(conceptDigest(Object.assign({}, c, { localizedLabels: { ro: "presentation" } }))).toBe(c.specificationDigest);
      for (const r of c.canonicalValues ?? []) expect(r.semanticVersion).toBe(pack.specificationVersion);
    }
    for (const v of pack.canonicalValues) {
      expect(v.semanticVersion).toBe(pack.specificationVersion);
      expect(canonicalValueDigest({ ...v, semanticVersion: "1.0.0-t162c2a" })).toBe(v.semanticDigest);
    }
  });
  it.each([["SECTION", "haircutting.section"], ["SUBSECTION", "haircutting.subsection"]])("keeps scope %s orthogonal to identity %s", (scope, id) => {
    expect(isProfessionalScope(scope)).toBe(true);
    expect(isConceptId(scope)).toBe(false);
    expect(isConceptId(id)).toBe(true);
    expect(isProfessionalScope(id)).toBe(false);
    const c = pack.concepts.find(c => c.conceptId === id)!;
    expect(c.scope).toBe(PROFESSIONAL_VALIDATION_REQUIRED);
    expect(isProfessionalConcept({ ...c, scope: id })).toBe(false);
    expect(isProfessionalConcept({ ...c, conceptId: scope })).toBe(false);
  });
  it.each([
    ["section", "subsection"], ["subsection", "subsectioning"], ["parting", "sectioning"],
    ["projection", "elevation"], ["overdirection", "projection"], ["overdirection", "guide"],
    ["guide", "guideType"], ["elevation", "cuttingAngle"], ["elevation", "cuttingLine"], ["cuttingAngle", "cuttingLine"],
  ])("preserves separate identities %s and %s without asserting relationships", (a, b) => {
    const first = pack.concepts.find(c => c.conceptId === `haircutting.${a}`)!;
    const second = pack.concepts.find(c => c.conceptId === `haircutting.${b}`)!;
    expect(first).toBeDefined(); expect(second).toBeDefined();
    expect(first.conceptId).not.toBe(second.conceptId);
    expect(first.specificationDigest).not.toBe(second.specificationDigest);
    expect(first.relationships).toEqual([]); expect(second.relationships).toEqual([]);
  });
  it("preserves legacy umbrellas and gives no new guide values or aliases", () => {
    for (const name of ["sectioning", "guideType"]) expect(pack.concepts.find(c => c.canonicalName === name)?.status).toBe("AMBIGUOUS");
    expect(pack.canonicalValues).toHaveLength(14);
    for (const token of ["stationary", "traveling"]) {
      const v = pack.canonicalValues.find(v => v.valueToken === token)!;
      expect(v.conceptId).toBe("haircutting.guideType");
      expect(v.status).toBe("AMBIGUOUS");
      expect(v.legacyMappingCorrespondence?.[0].correspondence).toBe("PARTIAL");
    }
    expect(pack.canonicalValues.some(v => v.conceptId === "haircutting.guide")).toBe(false);
    expect(pack.canonicalValues.every(v => v.legacyAliases === undefined)).toBe(true);
    expect(pack.concepts.every(c => c.legacyMappings?.length === 0 && c.relationships?.length === 0)).toBe(true);
  });
  it("does not move overdirection vocabulary or conflate guide mobility with it", () => {
    expect(ELEVATION_OPTIONS).toContain("180_deg_overdirection");
    expect(DISTRIBUTION_OPTIONS).toEqual(expect.arrayContaining(["overdirected_back", "overdirected_forward"]));
    expect(pack.canonicalValues.find(v => v.valueToken === "180_deg_overdirection")?.conceptId).toBe("haircutting.elevation");
    expect(GUIDE_BEHAVIORS).toEqual(["STATIONARY", "TRAVELLING", "UNKNOWN"]);
    expect(OVERDIRECTION_RELATIONSHIPS).toEqual(["TOWARD_GUIDE", "AWAY_FROM_GUIDE", "NONE_OBSERVED", "UNKNOWN"]);
    expect(pack.canonicalValues.some(v => v.conceptId === "haircutting.overdirection")).toBe(false);
  });
  it("retains all seven independent Skill guide dimensions without registering them", () => {
    const source = readFileSync("src/lib/professional-skill-guide-relationship-contracts.ts", "utf8");
    const ast = ts.createSourceFile("guide.ts", source, ts.ScriptTarget.Latest, true);
    const contract = ast.statements.find(s => ts.isInterfaceDeclaration(s) && s.name.text === "GuideRelationshipCapability") as ts.InterfaceDeclaration;
    // Identity, free-text note and the unknown-number ledger are metadata,
    // not additional independent professional dimensions.
    const dimensions = contract.members.filter(ts.isPropertySignature).map(m => [m.name.getText(ast), m.type?.getText(ast)] as const).filter(([name]) => !["id", "note", "unknownNumericFields"].includes(name));
    expect(dimensions).toEqual([
      ["guideSource", "GuideSource"], ["guideRole", "GuideRole"], ["guideBehavior", "GuideBehavior"],
      ["currentSectionRelationship", "GuideSectionRelationship"], ["overdirectionRelationship", "OverdirectionRelationship"],
      ["progression", "GuideProgressionState"], ["referenceProgression", "ReferenceProgressionState"],
    ]);
    expect(pack.concepts.some(c => dimensions.some(([name]) => c.canonicalName === name))).toBe(false);
  });
  it("registers no professional definitions or private technique facts", () => {
    expect(pack.definitions).toEqual([]);
    expect(pack.canonicalValues.every(v => v.semanticMeaning === PROFESSIONAL_VALIDATION_REQUIRED)).toBe(true);
    expect(pack.concepts.every(c => c.scope === PROFESSIONAL_VALIDATION_REQUIRED && c.effectRole === undefined)).toBe(true);
    expect(JSON.stringify(pack)).not.toMatch(/45° Interior|45Interior|ownerUserId|fingerOrientation|strandRotation|inward.round|finishingOperation/);
  });
});
